name: ci-cd
run-name: ci-cd for jibi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install Dep
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
    - name: Run tests
      run:  python3 -m unittest  bakend/test_app/test.py