name: ci-cd
run-name: ci-cd for jibi

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install Dep
      working-directory: ./bakend
      run: |
            pip install -r requirements.txt
    - name: Run tests
      run:  python3 -m unittest ./bakend/test_app/test.py
  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        working-directory: ./bakend
        run: docker build -f Dockerfile -t jibi:latest .